added solution for task 1 and 2
nastyasischuk/Task1-1-2 pull request #1
Opened 2019-09-20 19:57 UTC by nastyasischuk

2019-09-21 08:51 UTC, zhe1ezniak commented
Тут мне все нравится

2019-09-23 20:49 UTC, teaFunny requested changes

2019-09-23 20:49 UTC, teaFunny commented on src/itAcademy/task1/StartingCollectionPerThread.java
> +
Don`t use empty catch blocks

2019-09-23 20:49 UTC, teaFunny commented on src/itAcademy/task2/Main2.java
> +      System.out.println("First");
Check your code for duplications

2021-11-15 11:27 UTC, merged